movieproj/movieapp/urls.py
from django.urls import path
from . import views

app_name = 'movieapp'
urlpatterns = [
    path('', views.index, name="index"),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

movieproj/movieproj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieproj/movieapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproj/movieapp/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'desc', 'year', 'img']

movieproj/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from movieapp.forms import MovieForm
from movieapp.models import Movie


def index(request):
    movie = Movie.objects.all()
    context = {

        'movie_list': movie
    }
    return render(request, "index.html", context)


def detail(request, movie_id):
    # return HttpResponse("This is movie no %s" % movie_id)
    movie = Movie.objects.get(id=movie_id)
    return render(request, "details.html", {'movie': movie})


def add_movie(request):
    if request.method == "POST":
        name = request.POST.get('name', )
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        movie = Movie(name=name, desc=desc, year=year, img=img)
        movie.save()

    return render(request, "add.html")


def update(request, id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect("/")
    return render(request, "edit.html", {'form': form, 'movie': movie})


def delete(request, id):
    if request.method == "POST":
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect("/")
    return render(request,"delete.html")

movieproj/templates/add.html
{% extends 'base.html' %}
{% block body %}
<h2>Add your New Movie here</h2><br>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <input type="text" name="name" placeholder="Enter Your Movie Name "><br><br>
        <input type="text" name="desc" placeholder="Enter Your Movie Description "><br><br>

        <input type="number" name="year" placeholder="Enter Your Movie Year "><br><br>
        <input type="file" name="img" ><br><br>
        <input type="submit">
</form>
{% endblock %}

movieproj/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark" style="padding:20px;">
  <a class="navbar-brand" href="#" style="font-size:25px;">

  Online Movie Store

  </a>
    <a href="{% url 'movieapp:index' %}" style="font-size:18px;color:red;">Home</a>
    <a href="{% url 'movieapp:add_movie' %}" style="font-size:18px;color:red;">Add New Movie</a>
</nav>
<div class="container">
{% block body %}
{% endblock %}
</div>
</body>
</html>

movieproj/templates/delete.html
<form method="POST">
  {% csrf_token %}
  Do you want to Delete this movie?
  <input type="submit">
</form>

movieproj/templates/details.html
{% extends 'base.html'%}
{% block body %}
<h2 style="text-align:center;color:red;margin-top:20px;margin-bottom:30px;">Details of latest Movies</h2>
<div class="row">
    <div class="col-md-6">
<img src="{{movie.img.url}}" height="450" width="500">
        </div>
     <div class="col-md-6">
<h4 style="text-align:center;color:black">{{movie.name}}</h4><br>
<p style="color:blue">{{movie.desc}}</p><br>
<h5 style="color:black">{{movie.year}}</h5><br>
<a href="{% url 'movieapp:update' movie.id %}" class="btn btn-warning">update</a>
<a href="{% url 'movieapp:delete' movie.id %}" class="btn btn-danger">delete</a>
         </div>
</div>
    {% endblock %}

movieproj/templates/edit.html
{% extends 'base.html'%}
{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
{% endblock %}

movieproj/templates/index.html
{% extends 'base.html' %}
{% block body %}
<h2 style="text-align:center;color:blue; margin-top:20px;margin-bottom:10px;">Details of latest Movies</h2>
<div class="row">

    {% for i in movie_list %}
    <div class="col-md-4">
        <div class="card" style="width: 18rem; margin-bottom:20px;margin-top:20px;">
            <img src="{{ i.img.url }}" width="300px" height="300px" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title" style="color:black">{{i.name}}</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">{{i.name}}</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}
<!--<img src="{{ i.img.url }}" width="100" height="100">-->
<!--<a href="{% url 'movieapp:detail' i.id %}">{{i.name}}<br>-->